running slim version of test while working on git commit of visualization and figshare links.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,98 +7,99 @@ on:
 
 
 jobs:
-  build-hcmi-samples:
-    if: github.actor != 'github-actions[bot]'
-    runs-on: ubuntu-20.04
-    environment: build
-    steps:
-      #Add upload artifact from CPTAC Samples 
-      - name: Checkout  HCMI
-        uses: actions/checkout@v2
-      - name: Build HCMI Image
-        run: docker build -t hcmi-samples-builder -f build/docker/Dockerfile.hcmi.samples .
-      - name: Run HCMI Container
-        run: docker run --name hcmi-samples-container hcmi-samples-builder
-      - name: Copy file from HCMI Samples Container
-        run: |
-          mkdir hcmi-samples
-          for file in hcmi_samples.csv; do
-            docker cp hcmi-samples-container:/usr/src/app/$file hcmi-samples/$file
-          done
-      - name: Get HCMI container logs
-        run: docker logs hcmi-samples-container 
-      # - name: dummy hcmi
-      #   run: |
-      #     mkdir hcmi-files
-      #     echo "This is some sample text." > hcmi-files/d.txt
-      #     echo "Another line of text." > hcmi-files/c.gz
-      - name: Upload artifacts for HCMI
-        uses: actions/upload-artifact@v2
-        with:
-          name: hcmi-samples
-          path: hcmi-samples
+  # build-hcmi-samples:
+  #   if: github.actor != 'github-actions[bot]'
+  #   runs-on: ubuntu-20.04
+  #   environment: build
+  #   steps:
+  #     #Add upload artifact from CPTAC Samples 
+  #     - name: Checkout  HCMI
+  #       uses: actions/checkout@v2
+  #     - name: Build HCMI Image
+  #       run: docker build -t hcmi-samples-builder -f build/docker/Dockerfile.hcmi.samples .
+  #     - name: Run HCMI Container
+  #       run: docker run --name hcmi-samples-container hcmi-samples-builder
+  #     - name: Copy file from HCMI Samples Container
+  #       run: |
+  #         mkdir hcmi-samples
+  #         for file in hcmi_samples.csv; do
+  #           docker cp hcmi-samples-container:/usr/src/app/$file hcmi-samples/$file
+  #         done
+  #     - name: Get HCMI container logs
+  #       run: docker logs hcmi-samples-container 
+  #     # - name: dummy hcmi
+  #     #   run: |
+  #     #     mkdir hcmi-files
+  #     #     echo "This is some sample text." > hcmi-files/d.txt
+  #     #     echo "Another line of text." > hcmi-files/c.gz
+  #     - name: Upload artifacts for HCMI
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: hcmi-samples
+  #         path: hcmi-samples
 
-  build-hcmi:
-    if: github.actor != 'github-actions[bot]'
-    needs: [build-hcmi-samples]
-    runs-on: ubuntu-20.04
-    environment: build
-    steps:
-      - name: Checkout  HCMI
-        uses: actions/checkout@v2
-      - name: Download artifacts from HCMI
-        uses: actions/download-artifact@v2
-        with:
-          name: hcmi-samples
-      - name: List files cwd
-        run: ls -lah 
-      - name: Build HCMI Image
-        run: docker build -t hcmi-builder -f build/docker/Dockerfile.hcmi .
-      - name: Run HCMI Container
-        run: docker run --name hcmi-container hcmi-builder
-      - name: Copy files from HCMI Container
-        run: |
-          mkdir hcmi-files
-          for file in hcmi_samples.csv hcmi_transcriptomics.csv hcmi_copy_number.csv hcmi_mutations.csv; do
-            docker cp hcmi-container:/usr/src/app/$file hcmi-files/$file
-          done
-      - name: Get HCMI container logs
-        run: docker logs hcmi-container
-      # - name: dummy hcmi
-      #   run: |
-      #     mkdir hcmi-files
-      #     echo "This is some sample text." > hcmi-files/d.txt
-      #     echo "Another line of text." > hcmi-files/c.gz
-      - name: Upload artifacts for HCMI
-        uses: actions/upload-artifact@v2
-        with:
-          name: hcmi-files
-          path: hcmi-files
+  # build-hcmi:
+  #   if: github.actor != 'github-actions[bot]'
+  #   needs: [build-hcmi-samples]
+  #   runs-on: ubuntu-20.04
+  #   environment: build
+  #   steps:
+  #     - name: Checkout  HCMI
+  #       uses: actions/checkout@v2
+  #     - name: Download artifacts from HCMI
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: hcmi-samples
+  #     - name: List files cwd
+  #       run: ls -lah 
+  #     - name: Build HCMI Image
+  #       run: docker build -t hcmi-builder -f build/docker/Dockerfile.hcmi .
+  #     - name: Run HCMI Container
+  #       run: docker run --name hcmi-container hcmi-builder
+  #     - name: Copy files from HCMI Container
+  #       run: |
+  #         mkdir hcmi-files
+  #         for file in hcmi_samples.csv hcmi_transcriptomics.csv hcmi_copy_number.csv hcmi_mutations.csv; do
+  #           docker cp hcmi-container:/usr/src/app/$file hcmi-files/$file
+  #         done
+  #     - name: Get HCMI container logs
+  #       run: docker logs hcmi-container
+  #     # - name: dummy hcmi
+  #     #   run: |
+  #     #     mkdir hcmi-files
+  #     #     echo "This is some sample text." > hcmi-files/d.txt
+  #     #     echo "Another line of text." > hcmi-files/c.gz
+  #     - name: Upload artifacts for HCMI
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: hcmi-files
+  #         path: hcmi-files
 
-  build-beataml:
-    if: github.actor != 'github-actions[bot]'
-    runs-on: ubuntu-20.04
-    environment: build
-    steps:
-      - name: Checkout code BeatAML
-        uses: actions/checkout@v2
-      - name: Build BeatAML Image
-        run: docker build -t beataml-builder -f build/docker/Dockerfile.beataml .
-      - name: Run BeatAML Container
-        run: docker run --name beataml-container -e SYNAPSE_TOKEN=${{ secrets.SYNAPSE_TOKEN_SECRET }} beataml-builder
-      - name: Copy files from BeatAML Container
-        run: |
-          mkdir beataml-files
-          for file in beataml_samples.csv beataml_transcriptomics.csv beataml_proteomics.csv beataml_mutations.csv beataml_drugs.tsv beataml_experiments.csv; do
-            docker cp beataml-container:/usr/src/app/$file beataml-files/$file
-          done
-      - name: Get BeatAML container logs
-        run: docker logs beataml-container
-      - name: Upload artifact for BeatAML
-        uses: actions/upload-artifact@v2
-        with:
-          name: beataml-files
-          path: beataml-files
+  # build-beataml:
+  #   if: github.actor != 'github-actions[bot]'
+  #   runs-on: ubuntu-20.04
+  #   environment: build
+  #   steps:
+  #     - name: Checkout code BeatAML
+  #       uses: actions/checkout@v2
+  #     - name: Build BeatAML Image
+  #       run: docker build -t beataml-builder -f build/docker/Dockerfile.beataml .
+  #     - name: Run BeatAML Container
+  #       run: docker run --name beataml-container -e SYNAPSE_TOKEN=${{ secrets.SYNAPSE_TOKEN_SECRET }} beataml-builder
+  #     - name: Copy files from BeatAML Container
+  #       run: |
+  #         mkdir beataml-files
+  #         for file in beataml_samples.csv beataml_transcriptomics.csv beataml_proteomics.csv beataml_mutations.csv beataml_drugs.tsv beataml_experiments.csv; do
+  #           docker cp beataml-container:/usr/src/app/$file beataml-files/$file
+  #         done
+  #     - name: Get BeatAML container logs
+  #       run: docker logs beataml-container
+  #     - name: Upload artifact for BeatAML
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: beataml-files
+  #         path: beataml-files
+
   data-visualization:
     if: github.actor != 'github-actions[bot]'
     needs: [build-hcmi, build-beataml]
@@ -129,12 +130,12 @@ jobs:
           name: beataml-files
       - name: Install coderdata and skip build steps
         run: pip install coderdata
-      - name: Download cptac data from coder data
-        run: coderdata download --prefix cptac
-      - name: Download cell_line data from coder data
-        run: coderdata download --prefix cell_line
-      # - name: Download beataml data from coder data
-      #   run: coderdata download --prefix beataml
+      # - name: Download cptac data from coder data
+      #   run: coderdata download --prefix cptac
+      # - name: Download cell_line data from coder data
+      #   run: coderdata download --prefix cell_line
+      - name: Download all data from coder data
+        run: coderdata download 
       - name: Create all-files directory
         run: mkdir all-files
       - name: List files cwd
@@ -144,9 +145,9 @@ jobs:
       - name: Run Visualization01
         if: success() || failure()
         run: Rscript dataSummary/visualization01.R
-      - name: Run Visualization02
-        if: success() || failure()
-        run: Rscript dataSummary/visualization02.R
+      # - name: Run Visualization02
+      #   if: success() || failure()
+        # run: Rscript dataSummary/visualization02.R
       - name: setup data-vis dir
         if: success() || failure()
         run: |
@@ -191,6 +192,7 @@ jobs:
           git config user.email "jeremy.jacobson3402@gmail.com"
       - name: Commit and push changes
         run: |
+          git pull
           git add docs
           git commit -m "Add data visualization artifacts to docs"
           git push
@@ -240,6 +242,7 @@ jobs:
       - name: Commit and push changes
         run: |
           mv figshare_latest.yml docs
+            git pull
           git add docs
           git commit -m "Add figshare stats to docs"
           git push
